<a href="https://colab.research.google.com/github/KhantPhyo/ord_numpy/blob/main/1.%20np_ndarray_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_object.htm
import numpy as np

The numpy.array function in NumPy is used to create an array. Here is a breakdown of its parameters:
numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)



In [2]:
mylist = [1,2,3]
print(mylist)

[1, 2, 3]


object: This is the input data that you want to convert to an array. It can be a list, tuple, or any other array-like object.

dtype (optional): This parameter specifies the desired data type of the array elements. If not provided, NumPy will infer the data type from the input data.

copy (optional): This is a boolean flag indicating whether to create a copy of the input data. If set to True (default), a new copy is created. If set to False, the array will refer to the same data as the input.

order (optional): This parameter specifies the memory layout of the array. It can be 'C' for C-style (row-major) or 'F' for Fortran-style (column-major). If not provided, the default is 'C'.

subok (optional): This is a boolean flag. If set to True, sub-classes will be passed through. If set to False (default), the array will be forced to be a base-class array (e.g., ndarray).

ndmin (optional): This parameter specifies the minimum number of dimensions the resulting array should have. If not provided, the array will have the minimum number of dimensions needed to represent the data.

In [3]:
#https://discuss.boardinfinity.com/t/what-are-tensors/19073
a = np.array(mylist)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1 2 3]
(3,)
1
int64


In [ ]:
mylist = [[1, 2], [3, 4]]
print(mylist)
a = np.array(mylist)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2)
2
int64


In [8]:
mylist = [1, 2, 3,4,5]
print('List variable : ',mylist)
a = np.array(mylist, ndmin = 1)
print('ndmin - 1, ',a)
a = np.array(mylist, ndmin = 3)
print('ndmin - 3, ',a)
a = np.array(mylist, ndmin = 2)
print('ndmin - 2, ',a)
print('numpy : ', a)
print(a.shape)
print(a.ndim)
print(a.dtype)

List variable :  [1, 2, 3, 4, 5]
ndmin - 1,  [1 2 3 4 5]
ndmin - 3,  [[[1 2 3 4 5]]]
ndmin - 2,  [[1 2 3 4 5]]
numpy :  [[1 2 3 4 5]]
(1, 5)
2
int64


In [ ]:
mylist = [1., 2., 3.,4.,5.]
print(mylist)
a = np.array(mylist, ndmin = 2)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1.0, 2.0, 3.0, 4.0, 5.0]
[[1. 2. 3. 4. 5.]]
(1, 5)
2
float64


In [ ]:
mylist = [1, 2, 3]
print(mylist)
a = np.array(mylist, dtype = complex)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1, 2, 3]
[1.+0.j 2.+0.j 3.+0.j]
(3,)
1
complex128
