<a href="https://colab.research.google.com/github/KhantPhyo/ord_numpy/blob/main/3.%20np_array_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#https://www.tutorialspoint.com/numpy/numpy_array_attributes.htm
import numpy as np

In [2]:
mylist = [[1,2,3],[4,5,6]]
print(mylist)
a = np.array(mylist)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


shape of a converted from (2,3) to (3,2).

In [ ]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


We can also use reshape function.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.arange.html
#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
a = np.arange(24)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
int64


In [ ]:
b = a.reshape(2,4,3)
print(b)
print(b.shape)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)
3


1 byte - 8bits

In [3]:
mylist = [1,2,3,4,5]
print(mylist)
x = np.array(mylist, dtype = np.int8)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
(5,)
1
int8
1


32bits - 4 bytes

In [5]:
x = np.array(mylist, dtype = np.float32)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[1. 2. 3. 4. 5.]
(5,)
1
float32
4
